language: python
python:
  - 2.7

install:
  - sudo apt-get install libboost-python-dev libboost-thread-dev libboost-system-dev
  - sudo apt-get install systemtap-sdt-dev
  - pip install -e .
  - pip install -r requirements.pip

script:
    - py.test --cov v8 -s

after_success:
  - coveralls
